'use client'

import { useState } from 'react'
import { ArrowUpRight, Award, BookOpen, BriefcaseBusiness, Check, Code2, ExternalLink, GraduationCap, Mail, Menu, Moon, Play, Send, Sparkles, Sun, X } from 'lucide-react'
import { portfolio } from '@/lib/portfolio-data'

const nav = [['About','about'],['Skills','skills'],['Projects','projects'],['Internships','internships'],['Education','education'],['Resume','resume'],['Contact','contact']]
const icons = [Code2, Sparkles, BookOpen, BriefcaseBusiness, Award]
function Section({ id, eyebrow, title, children }: { id: string; eyebrow: string; title: string; children: React.ReactNode }) { return <section id={id} className="section-wrap"><div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{children}</section> }
function Pill({ children }: { children: React.ReactNode }) { return <span className="pill">{children}</span> }

export default function Page() {
  const [menu, setMenu] = useState(false); const [light, setLight] = useState(false); const [sent, setSent] = useState(false)
  const toggle = () => { setLight(!light); document.documentElement.classList.toggle('light', !light) }
  return <div className={light ? 'site light' : 'site'}>
    <header className="nav"><a href="#home" className="logo">{portfolio.initials}<span>.</span></a><nav className={menu ? 'nav-links open' : 'nav-links'}>{nav.map(([label,id]) => <a key={id} href={id === 'resume' ? portfolio.resumeUrl : `#${id}`} onClick={() => setMenu(false)}>{label}</a>)}</nav><div className="nav-actions"><button className="icon-btn" aria-label="Toggle theme" onClick={toggle}>{light ? <Moon size={17}/> : <Sun size={17}/>}</button><a className="resume-small" href={portfolio.resumeUrl}>Resume <ArrowUpRight size={15}/></a><button className="menu-btn icon-btn" aria-label="Toggle menu" onClick={() => setMenu(!menu)}>{menu ? <X size={20}/> : <Menu size={20}/>}</button></div></header>
    <main>
      <section id="home" className="hero"><div className="hero-copy"><div className="status"><i/> {portfolio.availability}</div><p className="eyebrow">Hello, I&apos;m</p><h1 className="hero-name"><span>{portfolio.name}</span></h1><p className="hero-title">{portfolio.title}</p><p className="hero-desc">{portfolio.bio}</p><div className="hero-actions"><a className="button primary" href="#projects">View My Projects <ArrowUpRight size={17}/></a><a className="button secondary" href={portfolio.resumeUrl}>Download Resume <ArrowUpRight size={17}/></a></div><div className="socials"><span>Find me on</span><a href={portfolio.socials.github} aria-label="GitHub"><Code2 size={18}/></a><a href={portfolio.socials.linkedin} aria-label="LinkedIn"><BriefcaseBusiness size={18}/></a><a href={`mailto:${portfolio.email}`} aria-label="Email"><Mail size={18}/></a></div></div><div className="hero-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="profile-wrap"><img src={portfolio.profileImage} alt={`${portfolio.name} profile portrait`} /></div><span className="spark spark-a">✦</span><span className="spark spark-b">+</span></div></section>
      <Section id="about" eyebrow="01 / About me" title="Learning in public, building with purpose."><div className="about-grid"><div><p className="big-copy">{portfolio.about}</p><p className="muted">My portfolio is a snapshot of the questions I&apos;m exploring, the tools I&apos;m practicing, and the small ideas I&apos;m turning into working software.</p></div><div className="stats">{[['2nd Year','B.Tech CSE'],['AI & ML','Specialization / Interest'],['Projects','Growing Portfolio'],['Learning','Every Day']].map(([a,b]) => <div className="stat" key={a}><strong>{a}</strong><span>{b}</span></div>)}</div></div></Section>
      <Section id="skills" eyebrow="02 / Toolkit" title="Technologies I&apos;m exploring."><div className="skills-layout"><div className="skill-grid">{Object.entries(portfolio.skills).map(([cat,items],i) => { const Icon=icons[i]; return <div className="glass skill-group" key={cat}><div className="group-head"><Icon size={18}/><span>{cat === 'ai' ? 'AI / ML' : cat === 'web' ? 'Web Development' : cat[0].toUpperCase()+cat.slice(1)}</span></div><div className="pills">{items.map(x=><Pill key={x}>{x}</Pill>)}</div></div> })}</div><div className="learning-panel"><div className="eyebrow">Currently learning</div>{['Data Structures & Algorithms','Machine Learning','C++','SQL','Deep Learning'].map((x,i)=><div className="learn-line" key={x}><span><i/> {x}</span><span className="in-progress">in progress</span></div>)}</div></div></Section>
      <Section id="projects" eyebrow="03 / Selected work" title="Small projects, real lessons."><div className="project-grid">{portfolio.projects.map((project,i)=><article className="project-card glass" key={`${project.title}-${i}`} role="link" tabIndex={0} aria-label={`Open live demo for ${project.title}`} onClick={(event) => { if ((event.target as HTMLElement).closest('a')) return; window.open(project.demoUrl, '_blank', 'noopener,noreferrer') }} onKeyDown={(event) => { if ((event.key === 'Enter' || event.key === ' ') && !(event.target as HTMLElement).closest('a')) { event.preventDefault(); window.open(project.demoUrl, '_blank', 'noopener,noreferrer') } }}><div className={`project-art art-${i}`}><img src={project.image} alt={`${project.title} project thumbnail`} onError={(event) => { event.currentTarget.style.display = 'none' }} /><span>{['01','02','03','04'][i]}</span></div><div className="project-body"><div className="placeholder-label">Sample project · replace with your work</div><h3>{project.title}</h3><p>{project.description}</p><div className="project-foot"><div className="tagline">{project.tags}</div><div className="card-links">{project.githubUrl && project.githubUrl !== 'YOUR_GITHUB_REPO_URL' && <a href={project.githubUrl} target="_blank" rel="noopener noreferrer" aria-label={`GitHub repository for ${project.title}`}><Code2 size={17}/></a>}<a href={project.demoUrl} target="_blank" rel="noopener noreferrer" aria-label={`Live demo for ${project.title}`}><ExternalLink size={17}/></a></div></div></div></article>)}</div></Section>
      <Section id="internships" eyebrow="04 / Experience in progress" title="Learning beyond the classroom."><div className="timeline">{portfolio.internships.map(([role,org,duration,skills,desc])=><div className="timeline-item glass" key={role}><div className="timeline-dot"/><div className="timeline-top"><div><span className="placeholder-label">Placeholder — replace details</span><h3>{role}</h3><p className="accent-text">{org}</p></div><span className="date">{duration}</span></div><p>{desc}</p>{skills && <div className="pills">{skills.split(' · ').map(s=><Pill key={s}>{s}</Pill>)}</div>}</div>)}</div></Section>
      <div className="split-sections"><Section id="education" eyebrow="05 / Education" title="The foundation I&apos;m growing."><div className="education-timeline">{portfolio.educationTimeline.map((item,index)=><div className="education-timeline-item" key={`${item.degree}-${index}`}><div className="education-rail"><span className="education-dot"/></div><div className="education-card glass"><GraduationCap size={25}/><h3>{item.degree}</h3><p className="accent-text">{item.university}</p><div className="edu-meta"><span>{item.year}</span><span>{item.detail}</span></div>{index===0 && <div className="subject-list">{['Data Structures','OOP','DBMS','Computer Networks','Operating Systems','AI / ML'].map(x=><Pill key={x}>{x}</Pill>)}</div>}</div></div>)}</div></Section></div>
      <Section id="certifications" eyebrow="06 / Certifications" title="Proof of the practice." ><div className="cert-grid">{portfolio.certificates.map((certificate,index)=>{ const hasImage=Boolean(certificate.image); const hasUrl=Boolean(certificate.certificateUrl); const preview=<div className="cert-image">{hasImage ? <img src={certificate.image} alt={`${certificate.title} certificate`} /> : <><Award size={30}/><span>Certificate image coming soon</span></>}</div>; return <div className="cert-card glass" key={`${certificate.title}-${index}`}>{hasUrl ? <a href={certificate.certificateUrl} target="_blank" rel="noopener noreferrer" aria-label={`Open ${certificate.title} certificate`}>{preview}</a> : preview}<span className="placeholder-label">{hasImage ? 'Certificate preview' : 'Placeholder certificate'}</span><h3>{certificate.title}</h3><p>{certificate.issuer} · {certificate.year}</p>{hasUrl ? <a href={certificate.certificateUrl} target="_blank" rel="noopener noreferrer" className="text-link">View certificate <ArrowUpRight size={15}/></a> : <span className="text-link disabled-link">Add certificate link <ArrowUpRight size={15}/></span>}</div>})}</div></Section>
      <Section id="learning" eyebrow="07 / The journey" title="Always one concept ahead."><div className="learning-grid">{portfolio.learning.map(([title,desc])=><div className="learning-card glass" key={title}><div className="learning-icon"><Sparkles size={17}/></div><h3>{title}</h3><p>{desc}</p><div className="progress-track"><span/></div></div>)}</div></Section>
      <Section id="contact" eyebrow="08 / Say hello" title="Let&apos;s build something together."><div className="contact-grid"><div><p className="big-copy">{`I'm always interested in learning, collaborating on projects, participating in hackathons, and exploring new technologies.`}</p><div className="contact-list"><a href={`mailto:${portfolio.email}`}><Mail size={19}/><span><small>Email:</small>{portfolio.email}</span></a><a href={portfolio.socials.github}><Code2 size={19}/><span><small>GitHub:</small>harshkumarsrivastava21-ui</span></a><a href={portfolio.socials.linkedin}><BriefcaseBusiness size={19}/><span><small>LinkedIn:</small>Harsh Kumar Srivastava</span></a><div><BookOpen size={19}/><span><small>Location</small>{portfolio.location}</span></div></div></div><form className="contact-form glass" onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent ? <div className="sent"><Check size={30}/><h3>Message ready to send.</h3><p>Connect a form endpoint to receive submissions.</p><button className="button secondary" type="button" onClick={()=>setSent(false)}>Send another</button></div> : <><input required placeholder="Name" aria-label="Name"/><input required type="email" placeholder="Email" aria-label="Email"/><input required placeholder="Subject" aria-label="Subject"/><textarea required placeholder="Message" aria-label="Message" rows={5}/><button className="button primary" type="submit">Send Message <Send size={16}/></button></>}</form></div></Section>
    </main><footer><a href="#home" className="logo">{portfolio.initials}<span>.</span></a><p>Built with curiosity, code, and continuous learning.</p><div className="socials"><a href={portfolio.socials.github}><Code2 size={17}/></a><a href={portfolio.socials.linkedin}><BriefcaseBusiness size={17}/></a><a href={`mailto:${portfolio.email}`}><Mail size={17}/></a></div><small>© 2026 Chandra Kanta Jena. All rights reserved.</small></footer>
  </div>
}
